version: '3.8'

services:
  backend:
    build:
      context: ./back-dotnet/DeepSeek
      dockerfile: Dockerfile
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ALLOWED_ORIGINS=http://localhost:3002
      - OLLAMA_API_BASE_URL=http://host.docker.internal:11434
  frontend:
    build:
      context: ./front/deepseek-ui
      args:
        - REACT_APP_API_BASE_URL=http://localhost:5100
        - REACT_APP_API_model=deepseek-r1:1.5b,deepseek-r1:7b,deepseek-r1:8b,deepseek-r1:14b,deepseek-r1:32b,deepseek-r1:70b,deepseek-r1:671b
    ports:
      - "3002:80"